/**
 * 球队别名表
 * ──────────────────────────────────────────────────
 * 把不同数据源(竞彩官方/Sina/API-Football/ClubElo/英文 BBC)
 * 的球队中英文写法归一到同一个 canonical key,
 * 让 prediction-engine / dixon-coles-engine 在跨源 join 时不漏匹配。
 *
 * 设计原则:
 *   - normalizeRaw() 把任意原始字符串做"无符号、无空格、小写"处理,
 *     得到 lookup key。再到 ALIAS_TABLE 查 canonical。
 *   - canonical 也会落到 normalizeRaw 之后的形态(全小写、无符号),
 *     这样 fixture-store 的 id 生成、market-data-store 的 fixture 匹配,
 *     都不会再因为 "拜仁" / "拜仁慕尼黑" / "Bayern" / "FC Bayern München" 分裂。
 *   - 不在表里的球队,直接返回 normalizeRaw 后的原值,行为与旧代码兼容,
 *     不影响未覆盖的小联赛。
 *
 * 维护规则:每加一个联赛或一支队,在 ALIAS_TABLE 里写一行映射,
 * 不要在调用方再写 if/switch。
 */

export function normalizeRaw(value) {
  return String(value ?? "").toLowerCase().normalize("NFKD").replace(/[^a-z0-9一-鿿]+/g, "");
}

export function canonicalTeamName(value) {
  const key = normalizeRaw(value);
  return ALIAS_TABLE[key] ?? key;
}

// 一对一映射:lookup-key(normalizeRaw 后) → canonical-key(也是 normalizeRaw 后形态)
// canonical 选用最常见的中文短名(无空格),英文源也一律归到这里。
const RAW_ALIASES = {
  // ───── 英超 ─────
  "曼联": "曼联", "曼彻斯特联": "曼联", "manunited": "曼联", "manchesterunited": "曼联",
  "曼城": "曼城", "曼彻斯特城": "曼城", "mancity": "曼城", "manchestercity": "曼城",
  "利物浦": "利物浦", "liverpool": "利物浦",
  "阿森纳": "阿森纳", "arsenal": "阿森纳",
  "切尔西": "切尔西", "chelsea": "切尔西",
  "热刺": "热刺", "托特纳姆": "热刺", "托特纳姆热刺": "热刺", "tottenham": "热刺", "spurs": "热刺",
  "纽卡斯尔": "纽卡斯尔", "纽卡": "纽卡斯尔", "newcastle": "纽卡斯尔",
  "维拉": "阿斯顿维拉", "阿斯顿维拉": "阿斯顿维拉", "astonvilla": "阿斯顿维拉",
  "西汉姆": "西汉姆", "westham": "西汉姆",
  "布莱顿": "布莱顿", "brighton": "布莱顿",
  "水晶宫": "水晶宫", "crystalpalace": "水晶宫",
  "富勒姆": "富勒姆", "fulham": "富勒姆",
  "狼队": "狼队", "wolves": "狼队", "wolverhampton": "狼队",
  "诺丁汉森林": "诺丁汉森林", "诺丁汉": "诺丁汉森林", "nottinghamforest": "诺丁汉森林",
  "埃弗顿": "埃弗顿", "everton": "埃弗顿",
  "布伦特福德": "布伦特福德", "brentford": "布伦特福德",
  "伯恩茅斯": "伯恩茅斯", "bournemouth": "伯恩茅斯",
  "莱斯特城": "莱斯特", "莱斯特": "莱斯特", "leicester": "莱斯特",
  "伊普斯维奇": "伊普斯维奇", "ipswich": "伊普斯维奇",
  "南安普顿": "南安普顿", "southampton": "南安普顿",

  // ───── 西甲 ─────
  "皇马": "皇马", "皇家马德里": "皇马", "realmadrid": "皇马",
  "巴萨": "巴萨", "巴塞罗那": "巴萨", "barcelona": "巴萨", "fcbarcelona": "巴萨",
  "马竞": "马竞", "马德里竞技": "马竞", "atleticomadrid": "马竞", "atletico": "马竞",
  "马洛卡": "马洛卡", "皇家马洛卡": "马洛卡", "mallorca": "马洛卡",
  "塞维利亚": "塞维利亚", "sevilla": "塞维利亚",
  "皇家社会": "皇家社会", "realsociedad": "皇家社会",
  "毕尔巴鄂": "毕尔巴鄂", "毕尔巴鄂竞技": "毕尔巴鄂", "athleticbilbao": "毕尔巴鄂", "athletic": "毕尔巴鄂",
  "维戈塞尔塔": "塞尔塔", "塞尔塔": "塞尔塔", "celtavigo": "塞尔塔", "celta": "塞尔塔",
  "皇家贝蒂斯": "贝蒂斯", "贝蒂斯": "贝蒂斯", "realbetis": "贝蒂斯",
  "比利亚雷亚尔": "比利亚雷亚尔", "黄潜": "比利亚雷亚尔", "villarreal": "比利亚雷亚尔",
  "瓦伦西亚": "瓦伦西亚", "valencia": "瓦伦西亚",
  "赫罗纳": "赫罗纳", "girona": "赫罗纳",
  "巴列卡诺": "巴列卡诺", "rayovallecano": "巴列卡诺",
  "莱加内斯": "莱加内斯", "leganes": "莱加内斯",
  "拉斯帕尔马斯": "拉斯帕尔马斯", "laspalmas": "拉斯帕尔马斯",
  "奥萨苏纳": "奥萨苏纳", "osasuna": "奥萨苏纳",
  "赫塔费": "赫塔费", "getafe": "赫塔费",
  "阿拉维斯": "阿拉维斯", "alaves": "阿拉维斯",
  "巴拉多利德": "巴拉多利德", "valladolid": "巴拉多利德",
  "西班牙人": "西班牙人", "espanyol": "西班牙人",

  // ───── 德甲 ─────
  "拜仁慕尼黑": "拜仁", "拜仁": "拜仁", "bayernmunich": "拜仁", "fcbayern": "拜仁", "bayern": "拜仁",
  "多特蒙德": "多特", "多特": "多特", "borussiadortmund": "多特", "dortmund": "多特", "bvb": "多特",
  "勒沃库森": "勒沃库森", "leverkusen": "勒沃库森", "bayer04": "勒沃库森",
  "莱比锡": "莱比锡", "rbleipzig": "莱比锡", "leipzig": "莱比锡",
  "斯图加特": "斯图加特", "stuttgart": "斯图加特", "vfbstuttgart": "斯图加特",
  "法兰克福": "法兰克福", "eintrachtfrankfurt": "法兰克福", "frankfurt": "法兰克福",
  "霍芬海姆": "霍芬海姆", "hoffenheim": "霍芬海姆",
  "门兴": "门兴", "门兴格拉德巴赫": "门兴", "monchengladbach": "门兴", "borussiamg": "门兴", "gladbach": "门兴",
  "沃尔夫斯堡": "沃尔夫斯堡", "wolfsburg": "沃尔夫斯堡",
  "云达不莱梅": "不莱梅", "不莱梅": "不莱梅", "werderbremen": "不莱梅",
  "美因茨": "美因茨", "mainz05": "美因茨", "mainz": "美因茨",
  "弗赖堡": "弗赖堡", "freiburg": "弗赖堡", "scfreiburg": "弗赖堡",
  "奥格斯堡": "奥格斯堡", "augsburg": "奥格斯堡",
  "波鸿": "波鸿", "bochum": "波鸿",
  "圣保利": "圣保利", "stpauli": "圣保利", "fcstpauli": "圣保利",
  "海登海姆": "海登海姆", "heidenheim": "海登海姆",
  "基尔": "基尔", "holsteinkiel": "基尔",
  "联合柏林": "联合柏林", "unionberlin": "联合柏林",
  "霍尔斯坦基尔": "基尔",
  "帕德博恩": "帕德博恩", "paderborn": "帕德博恩",

  // ───── 意甲 ─────
  "国际米兰": "国米", "国米": "国米", "inter": "国米", "intermilan": "国米",
  "ac米兰": "ac米兰", "米兰": "ac米兰", "acmilan": "ac米兰",
  "尤文图斯": "尤文", "尤文": "尤文", "juventus": "尤文", "juve": "尤文",
  "罗马": "罗马", "asroma": "罗马",
  "拉齐奥": "拉齐奥", "lazio": "拉齐奥",
  "那不勒斯": "那不勒斯", "napoli": "那不勒斯",
  "亚特兰大": "亚特兰大", "atalanta": "亚特兰大",
  "佛罗伦萨": "佛罗伦萨", "fiorentina": "佛罗伦萨",
  "博洛尼亚": "博洛尼亚", "bologna": "博洛尼亚",
  "都灵": "都灵", "torino": "都灵",
  "热那亚": "热那亚", "genoa": "热那亚",
  "莱切": "莱切", "lecce": "莱切",
  "卡利亚里": "卡利亚里", "cagliari": "卡利亚里",
  "维罗纳": "维罗纳", "hellasverona": "维罗纳", "verona": "维罗纳",
  "乌迪内斯": "乌迪内斯", "udinese": "乌迪内斯",
  "蒙扎": "蒙扎", "monza": "蒙扎",
  "恩波利": "恩波利", "empoli": "恩波利",
  "科莫": "科莫", "como": "科莫",
  "威尼斯": "威尼斯", "venezia": "威尼斯",
  "帕尔马": "帕尔马", "parma": "帕尔马",

  // ───── 法甲 ─────
  // 中文体彩官方用"圣日尔曼"(尔),通用译法用"圣日耳曼"(耳)。两种简繁/异译都归到"巴黎"。
  "巴黎圣日耳曼": "巴黎", "巴黎圣日尔曼": "巴黎", "巴黎圣日耳曼足球俱乐部": "巴黎", "巴黎圣日尔曼足球俱乐部": "巴黎",
  "巴黎": "巴黎", "psg": "巴黎", "parissaintgermain": "巴黎",
  "马赛": "马赛", "marseille": "马赛", "om": "马赛",
  "里昂": "里昂", "lyon": "里昂", "olympiquelyonnais": "里昂", "ol": "里昂",
  "里尔": "里尔", "lille": "里尔", "losc": "里尔",
  "摩纳哥": "摩纳哥", "monaco": "摩纳哥",
  "尼斯": "尼斯", "nice": "尼斯", "ognice": "尼斯",
  "雷恩": "雷恩", "rennes": "雷恩",
  "图卢兹": "图卢兹", "toulouse": "图卢兹",
  "斯特拉斯堡": "斯特拉斯堡", "strasbourg": "斯特拉斯堡",
  "南特": "南特", "nantes": "南特",
  "兰斯": "兰斯", "reims": "兰斯",
  "蒙彼利埃": "蒙彼利埃", "montpellier": "蒙彼利埃",
  "布雷斯特": "布雷斯特", "brest": "布雷斯特",
  "勒阿弗尔": "勒阿弗尔", "lehavre": "勒阿弗尔",
  "圣埃蒂安": "圣埃蒂安", "saintetienne": "圣埃蒂安", "asse": "圣埃蒂安",
  "欧塞尔": "欧塞尔", "auxerre": "欧塞尔",
  "昂热": "昂热", "angers": "昂热",
  "朗斯": "朗斯", "lens": "朗斯",

  // ───── 挪超(本季实际推荐覆盖) ─────
  "博多格林特": "博多格林特", "bodoglimt": "博多格林特",
  "莫尔德": "莫尔德", "molde": "莫尔德",
  "罗森博格": "罗森博格", "rosenborg": "罗森博格",
  "瓦勒伦加": "瓦勒伦加", "valerenga": "瓦勒伦加",
  "维京": "维京", "viking": "维京",
  "布兰": "布兰", "brann": "布兰", "sk布兰": "布兰",
  "斯达": "斯达", "stromsgodset": "斯达", "stromsgodsetif": "斯达",
  "特罗姆瑟": "特罗姆瑟", "tromso": "特罗姆瑟",
  "奥勒松": "奥勒松", "aalesund": "奥勒松",
  "汉肯": "汉肯", "汉坎": "汉肯", "haugesund": "汉肯",
  "利勒斯特罗姆": "利勒斯特", "利勒斯特": "利勒斯特", "lillestrom": "利勒斯特",
  "萨普斯堡": "萨普斯堡", "萨尔普斯堡": "萨普斯堡", "sarpsborg": "萨普斯堡", "sarpsborg08": "萨普斯堡",
  "奥斯kfum": "奥斯kfum", "kfumoslo": "奥斯kfum",
  "桑纳菲": "桑纳菲", "sandefjord": "桑纳菲",
  "腓特烈": "腓特烈", "腓特烈斯塔": "腓特烈", "fredrikstad": "腓特烈",

  // ───── 瑞超 ─────(2026-05-31 补 ESPN 全名变体:ESPN 队名带 IF/BK/FF/AIF 后缀,
  //   规范化后与 football-data/竞彩 的裸名/中文名不一致,补齐才能让回填的瑞超赛果接上 DC 训练)
  "马尔默": "马尔默", "malmoff": "马尔默", "malmofotbolltlsforening": "马尔默", "malmo": "马尔默",
  "哥德堡": "哥德堡", "ifkgoteborg": "哥德堡", "goteborg": "哥德堡",
  "djurgardens": "尤尔加登", "djurgarden": "尤尔加登", "尤尔加登": "尤尔加登",
  "aikstockholm": "aik", "aik": "aik",
  "哈马比": "哈马比", "hammarby": "哈马比", "hammarbyif": "哈马比",
  "埃尔夫斯堡": "埃夫斯堡", "埃夫斯堡": "埃夫斯堡", "elfsborg": "埃夫斯堡", "ifelfsborg": "埃夫斯堡",
  "赫根": "赫根", "hacken": "赫根", "bkhacken": "赫根",
  "米亚尔比": "米亚尔比", "mjallby": "米亚尔比", "mjallbyaif": "米亚尔比",
  "诺尔切平": "诺尔切平", "norrkoping": "诺尔切平", "ifknorrkoping": "诺尔切平",
  "代格福什": "代格福什", "degerfors": "代格福什", "degerforsif": "代格福什",
  "布鲁马波卡纳": "布鲁马波卡纳", "布鲁马波": "布鲁马波卡纳", "brommapojkarna": "布鲁马波卡纳", "ifbrommapojkarna": "布鲁马波卡纳",
  "西里乌斯": "西里乌斯", "sirius": "西里乌斯", "iksirius": "西里乌斯",
  "哈尔姆斯塔德": "哈尔姆斯塔德", "halmstad": "哈尔姆斯塔德", "halmstads": "哈尔姆斯塔德", "halmstadsbk": "哈尔姆斯塔德",
  "厄斯特": "厄斯特", "osters": "厄斯特", "ostersif": "厄斯特",
  "韦纳默": "韦纳默", "varnamo": "韦纳默", "ifkvarnamo": "韦纳默",
  "gais": "gais", "gaisgoteborg": "gais",
  "韦斯特罗斯": "韦斯特罗斯", "vasteras": "韦斯特罗斯", "vasterassk": "韦斯特罗斯",

  // ───── 中超 ─────
  "上海海港": "海港", "海港": "海港", "shanghaiport": "海港",
  "上海申花": "申花", "申花": "申花", "shanghaishenhua": "申花",
  "山东泰山": "山东泰山", "shandongtaishan": "山东泰山",
  "北京国安": "国安", "国安": "国安", "beijingguoan": "国安",
  "成都蓉城": "成都蓉城", "chengdurongcheng": "成都蓉城",
  "浙江队": "浙江", "浙江": "浙江", "zhejiangfc": "浙江",
  "天津津门虎": "津门虎", "津门虎": "津门虎", "tianjinjinmentiger": "津门虎",
  "武汉三镇": "武汉三镇", "wuhanthreetowns": "武汉三镇",
  "长春亚泰": "长春亚泰", "changchunyatai": "长春亚泰",
  "深圳新鹏城": "新鹏城", "新鹏城": "新鹏城", "shenzhenxinpengcheng": "新鹏城",

  // ───── 芬超(本季有推荐) ─────
  "坦佩雷山猫": "坦山猫", "坦山猫": "坦山猫", "ilves": "坦山猫", "ilvestampere": "坦山猫",
  "赫尔辛基火花": "赫尔火花", "赫尔火花": "赫尔火花", "hjkhelsinki": "赫尔火花", "hjk": "赫尔火花",
  "塞伊奈约基": "塞伊奈", "塞伊奈": "塞伊奈", "seinajoki": "塞伊奈", "spsjk": "塞伊奈",
  "ac奥卢": "ac奥卢", "acoulu": "ac奥卢",
  "kupskuopio": "kups", "kups": "kups",

  // ───── 沙特联(ledger 出现频繁) ─────
  "alittihad": "伊蒂哈德", "伊蒂哈德": "伊蒂哈德",
  "alettifaq": "艾蒂法克", "艾蒂法克": "艾蒂法克",
  "alqadsiah": "卡迪西亚", "卡迪西亚": "卡迪西亚",
  "alhazem": "哈兹姆", "哈兹姆": "哈兹姆",
  "alnassr": "利雅得胜利", "利雅得胜利": "利雅得胜利",
  "alhilal": "利雅得新月", "利雅得新月": "利雅得新月",

  // ───── 巴甲 / 阿甲(14 场常见) ─────
  "弗拉门戈": "弗拉门戈", "flamengo": "弗拉门戈",
  "帕尔梅拉斯": "帕尔梅拉斯", "palmeiras": "帕尔梅拉斯",
  "科林蒂安": "科林蒂安", "corinthians": "科林蒂安",
  "圣保罗": "圣保罗", "saopaulo": "圣保罗",
  "弗鲁米嫩塞": "弗鲁米嫩塞", "fluminense": "弗鲁米嫩塞",
  "博塔弗戈": "博塔弗戈", "botafogo": "博塔弗戈",
  "格雷米奥": "格雷米奥", "gremio": "格雷米奥",
  "国际": "巴西国际", "巴西国际": "巴西国际", "internacional": "巴西国际",
  "普拉滕斯": "普拉滕斯", "platense": "普拉滕斯",
  "库斯科": "库斯科", "cuscofc": "库斯科",

  // ───── 旧映射保留(向后兼容) ─────
  "拜仁慕尼黑": "拜仁",

  // ───── 长形式/带前缀变体(覆盖 NFKD 去重音后的拼写) ─────
  "fcbayernmunchen": "拜仁", "bayernmunchen": "拜仁", "fcbayernmunich": "拜仁",
  "borussiadortmund": "多特", "bvbborussiadortmund": "多特",
  "manchesterunitedfc": "曼联", "manunitedfc": "曼联", "manchutd": "曼联",
  "manchestercityfc": "曼城", "mcfc": "曼城",
  "fcliverpool": "利物浦", "liverpoolfc": "利物浦",
  "arsenalfc": "阿森纳",
  "chelseafc": "切尔西",
  "tottenhamhotspur": "热刺", "tottenhamhotspurfc": "热刺",
  "atleticodemadrid": "马竞", "atletico madrid": "马竞", "atleti": "马竞",
  "realmadridcf": "皇马", "realmadridfc": "皇马",
  "fcbarcelonafc": "巴萨", "barcelonafc": "巴萨",
  "internazionale": "国米", "internazionalemilano": "国米", "fcinternazionalemilano": "国米", "intermilan": "国米",
  "associazionecalciomilan": "ac米兰", "milanac": "ac米兰",
  "juventusfc": "尤文",
  "parissaintgermainfc": "巴黎", "psgparissaintgermain": "巴黎",
  "olympiquedemarseille": "马赛",
  "olympiquelyonnais": "里昂",
  "stadebrest": "布雷斯特", "stadebrestois29": "布雷斯特",
  "ssclazio": "拉齐奥",
  "ssnapoli": "那不勒斯", "sscnapoli": "那不勒斯",

  // ───── V 档回填覆盖(OpenFootball 长全称 → 中文 canonical;同时补中文短名自映射,让竞彩场次也链得上) ─────
  // 英超
  "afcbournemouth": "伯恩茅斯", "伯恩茅斯": "伯恩茅斯", "bournemouth": "伯恩茅斯",
  "leicestercityfc": "莱斯特城", "莱斯特城": "莱斯特城", "莱斯特": "莱斯特城", "leicester": "莱斯特城",
  "fulhamfc": "富勒姆", "富勒姆": "富勒姆", "fulham": "富勒姆",
  "ipswichtownfc": "伊普斯维奇", "伊普斯维奇": "伊普斯维奇", "ipswich": "伊普斯维奇",
  "westhamunitedfc": "西汉姆", "西汉姆": "西汉姆", "西汉姆联": "西汉姆", "westham": "西汉姆", "westhamunited": "西汉姆",
  "crystalpalacefc": "水晶宫", "水晶宫": "水晶宫", "crystalpalace": "水晶宫",
  "astonvillafc": "阿斯顿维拉", "阿斯顿维拉": "阿斯顿维拉", "维拉": "阿斯顿维拉", "astonvilla": "阿斯顿维拉",
  "newcastleunitedfc": "纽卡斯尔", "newcastleunited": "纽卡斯尔",
  "evertonfc": "埃弗顿", "埃弗顿": "埃弗顿", "everton": "埃弗顿",
  "nottinghamforestfc": "诺丁汉森林", "诺丁汉森林": "诺丁汉森林", "诺丁汉": "诺丁汉森林", "nottinghamforest": "诺丁汉森林",
  "southamptonfc": "南安普顿", "南安普顿": "南安普顿", "southampton": "南安普顿",
  "brightonhovealbionfc": "布莱顿", "布莱顿": "布莱顿", "brighton": "布莱顿", "brightonhovealbion": "布莱顿",
  "wolverhamptonwanderersfc": "狼队", "狼队": "狼队", "伍尔弗汉普顿": "狼队", "wolves": "狼队", "wolverhampton": "狼队",
  "brentfordfc": "布伦特福德", "布伦特福德": "布伦特福德", "brentford": "布伦特福德",
  "burnleyfc": "伯恩利", "伯恩利": "伯恩利", "burnley": "伯恩利",
  "lutontownfc": "卢顿", "卢顿": "卢顿", "luton": "卢顿", "lutontown": "卢顿",
  "sheffieldunitedfc": "谢菲尔德联", "谢菲尔德联": "谢菲尔德联", "谢菲联": "谢菲尔德联", "sheffieldunited": "谢菲尔德联",
  // FPL 官方简写补全(Y 档 — 免授权伤停源队名对齐)
  "manutd": "曼联", "nottmforest": "诺丁汉森林",
  "leeds": "利兹联", "leedsunited": "利兹联", "leedsunitedfc": "利兹联", "利兹联": "利兹联", "利兹": "利兹联",
  "sunderland": "桑德兰", "sunderlandafc": "桑德兰", "桑德兰": "桑德兰",
  "sheffieldutd": "谢菲尔德联",
  // ───────── Z2 档:洲际/扩展联赛知名队 中文别名(免授权赛果源队名对齐)─────────
  // 中超(ESPN chn.1 英文名 → 中文)
  "beijingguoan": "北京国安", "北京国安": "北京国安", "国安": "北京国安",
  "changchunyatai": "长春亚泰", "长春亚泰": "长春亚泰",
  "chengdurongcheng": "成都蓉城", "成都蓉城": "成都蓉城",
  "dalianyingbo": "大连英博", "大连英博": "大连英博",
  "henansongshanlongmen": "河南", "河南": "河南", "河南嵩山龙门": "河南",
  "meizhouhakka": "梅州客家", "梅州客家": "梅州客家",
  "qingdaohainiu": "青岛海牛", "青岛海牛": "青岛海牛",
  "qingdaowestcoast": "青岛西海岸", "青岛西海岸": "青岛西海岸",
  "shandongtaishan": "山东泰山", "山东泰山": "山东泰山", "山东": "山东泰山",
  "shanghaiport": "上海海港", "上海海港": "上海海港", "海港": "上海海港",
  "shanghaishenhua": "上海申花", "上海申花": "上海申花", "申花": "上海申花",
  "shenzhenxinpengcheng": "深圳新鹏城", "深圳新鹏城": "深圳新鹏城",
  "tianjinjinmentiger": "天津津门虎", "天津津门虎": "天津津门虎", "天津": "天津津门虎",
  "wuhanthreetowns": "武汉三镇", "武汉三镇": "武汉三镇",
  "yunnanyukun": "云南玉昆", "云南玉昆": "云南玉昆",
  "zhejiangprofessionalfc": "浙江", "浙江": "浙江", "浙江职业": "浙江",
  // 日职(ESPN jpn.1)
  "albirexniigata": "新潟天鹅", "新潟天鹅": "新潟天鹅",
  "avispafukuoka": "福冈黄蜂", "福冈黄蜂": "福冈黄蜂",
  "cerezoosaka": "大阪樱花", "大阪樱花": "大阪樱花",
  "fctokyo": "东京FC", "东京fc": "东京FC",
  "fagianookayama": "冈山绿雉", "冈山绿雉": "冈山绿雉",
  "gambaosaka": "大阪钢巴", "大阪钢巴": "大阪钢巴",
  "kashimaantlers": "鹿岛鹿角", "鹿岛鹿角": "鹿岛鹿角",
  "kashiwareysol": "柏太阳神", "柏太阳神": "柏太阳神",
  "kawasakifrontale": "川崎前锋", "川崎前锋": "川崎前锋",
  "kyotosanga": "京都不死鸟", "京都不死鸟": "京都不死鸟", "京都桑加": "京都不死鸟",
  "machidazelvia": "町田泽尔维亚", "町田泽尔维亚": "町田泽尔维亚", "町田": "町田泽尔维亚",
  "nagoyagrampus": "名古屋鲸八", "名古屋鲸八": "名古屋鲸八",
  "sanfreccehiroshima": "广岛三箭", "广岛三箭": "广岛三箭",
  "shimizuspulse": "清水心跳", "清水心跳": "清水心跳",
  "shonanbellmare": "湘南海洋", "湘南海洋": "湘南海洋",
  "tokyoverdy1969": "东京绿茵", "tokyoverdy": "东京绿茵", "东京绿茵": "东京绿茵",
  "urawareddiamonds": "浦和红钻", "浦和红钻": "浦和红钻", "浦和红宝石": "浦和红钻",
  "visselkobe": "神户胜利船", "神户胜利船": "神户胜利船",
  "yokohamafmarinos": "横滨水手", "横滨水手": "横滨水手",
  "yokohamafc": "横滨FC", "横滨fc": "横滨FC",
  // 沙特联(ESPN ksa.1,知名队)
  "alhilal": "利雅得新月", "利雅得新月": "利雅得新月",
  "alnassr": "利雅得胜利", "利雅得胜利": "利雅得胜利",
  "alittihad": "吉达联合", "吉达联合": "吉达联合",
  "alahli": "吉达国民", "吉达国民": "吉达国民",
  "alshabab": "利雅得青年", "利雅得青年": "利雅得青年",
  "altaawoun": "塔阿文", "塔阿文": "塔阿文",
  "alqadsiah": "卡迪西亚", "卡迪西亚": "卡迪西亚",
  "alfateh": "法德", "法德": "法德",
  // 荷甲(football-data N1 英文名)
  "ajax": "阿贾克斯", "阿贾克斯": "阿贾克斯",
  "psveindhoven": "埃因霍温", "psv": "埃因霍温", "埃因霍温": "埃因霍温",
  "feyenoord": "费耶诺德", "费耶诺德": "费耶诺德",
  "azalkmaar": "阿尔克马尔", "az": "阿尔克马尔", "阿尔克马尔": "阿尔克马尔",
  "twente": "特温特", "特温特": "特温特",
  "utrecht": "乌德勒支", "乌德勒支": "乌德勒支",
  "heerenveen": "海伦芬", "海伦芬": "海伦芬",
  "groningen": "格罗宁根", "格罗宁根": "格罗宁根",
  "spartarotterdam": "鹿特丹斯巴达", "鹿特丹斯巴达": "鹿特丹斯巴达",
  "goaheadeagles": "飞鹰", "飞鹰": "飞鹰",
  "nacbreda": "布雷达", "布雷达": "布雷达",
  "heracles": "赫拉克勒斯", "赫拉克勒斯": "赫拉克勒斯",
  "willemii": "威廉二世", "威廉二世": "威廉二世",
  "almerecity": "阿尔梅勒城", "阿尔梅勒城": "阿尔梅勒城",
  "nijmegen": "奈梅亨", "奈梅亨": "奈梅亨",
  "zwolle": "兹沃勒", "兹沃勒": "兹沃勒",
  "waalwijk": "瓦尔韦克", "瓦尔韦克": "瓦尔韦克",
  "forsittard": "西塔德", "fortunasittard": "西塔德", "西塔德": "西塔德",
  // 葡超(football-data P1)
  "benfica": "本菲卡", "本菲卡": "本菲卡",
  "porto": "波尔图", "波尔图": "波尔图",
  "splisbon": "里斯本竞技", "sporting": "里斯本竞技", "sportingcp": "里斯本竞技", "里斯本竞技": "里斯本竞技", "葡萄牙体育": "里斯本竞技",
  "spbraga": "布拉加", "braga": "布拉加", "布拉加": "布拉加",
  "guimaraes": "吉马良斯", "吉马良斯": "吉马良斯",
  "boavista": "博阿维斯塔", "博阿维斯塔": "博阿维斯塔",
  "famalicao": "法马利康", "法马利康": "法马利康",
  "estoril": "埃斯托里尔", "埃斯托里尔": "埃斯托里尔",
  "rioave": "里奥阿维", "里奥阿维": "里奥阿维",
  "gilvicente": "吉尔维森特", "吉尔维森特": "吉尔维森特",
  "moreirense": "莫雷伦斯", "莫雷伦斯": "莫雷伦斯",
  "arouca": "阿罗卡", "阿罗卡": "阿罗卡",
  "casapia": "卡萨皮亚", "卡萨皮亚": "卡萨皮亚",
  "nacional": "国民", "国民": "国民",
  "santaclara": "圣克拉拉", "圣克拉拉": "圣克拉拉",
  "farense": "法伦斯", "法伦斯": "法伦斯",
  "estrela": "阿马多拉之星", "阿马多拉之星": "阿马多拉之星",
  // 比甲(football-data B1)
  "anderlecht": "安德莱赫特", "安德莱赫特": "安德莱赫特",
  "clubbrugge": "布鲁日", "布鲁日": "布鲁日",
  "genk": "亨克", "亨克": "亨克",
  "gent": "根特", "根特": "根特",
  "antwerp": "安特卫普", "安特卫普": "安特卫普",
  "standard": "标准列日", "标准列日": "标准列日",
  "cerclebrugge": "塞克尔布鲁日", "塞克尔布鲁日": "塞克尔布鲁日",
  "charleroi": "沙勒罗瓦", "沙勒罗瓦": "沙勒罗瓦",
  "mechelen": "梅赫伦", "梅赫伦": "梅赫伦",
  "struiden": "圣特鲁伊登", "sttruiden": "圣特鲁伊登", "圣特鲁伊登": "圣特鲁伊登",
  "stgilloise": "圣吉罗斯联", "unionsg": "圣吉罗斯联", "圣吉罗斯联": "圣吉罗斯联",
  "westerlo": "韦斯特洛", "韦斯特洛": "韦斯特洛",
  "kortrijk": "科特赖克", "科特赖克": "科特赖克",
  "oudheverleeleuven": "鲁汶", "ohleuven": "鲁汶", "鲁汶": "鲁汶",
  "beerschotva": "比尔斯霍特", "beerschot": "比尔斯霍特", "比尔斯霍特": "比尔斯霍特",
  "dender": "登德尔", "登德尔": "登德尔",
  // 西甲
  "clubatleticodemadrid": "马竞",
  "realbetisbalompie": "皇家贝蒂斯", "皇家贝蒂斯": "皇家贝蒂斯", "贝蒂斯": "皇家贝蒂斯", "realbetis": "皇家贝蒂斯", "betis": "皇家贝蒂斯",
  "rcceltadevigo": "塞尔塔", "塞尔塔": "塞尔塔", "celta": "塞尔塔", "celtavigo": "塞尔塔",
  "rayovallecanodemadrid": "巴列卡诺", "巴列卡诺": "巴列卡诺", "rayovallecano": "巴列卡诺",
  "villarrealcf": "比利亚雷亚尔", "比利亚雷亚尔": "比利亚雷亚尔", "villarreal": "比利亚雷亚尔",
  "sevillafc": "塞维利亚", "塞维利亚": "塞维利亚", "sevilla": "塞维利亚",
  "valenciacf": "瓦伦西亚", "瓦伦西亚": "瓦伦西亚", "valencia": "瓦伦西亚",
  "athleticclub": "毕尔巴鄂竞技", "毕尔巴鄂竞技": "毕尔巴鄂竞技", "毕尔巴鄂": "毕尔巴鄂竞技", "athleticbilbao": "毕尔巴鄂竞技",
  "rcdmallorca": "马略卡", "马略卡": "马略卡", "马洛卡": "马略卡", "mallorca": "马略卡",
  "getafecf": "赫塔费", "赫塔费": "赫塔费", "getafe": "赫塔费",
  "realsociedaddefutbol": "皇家社会", "皇家社会": "皇家社会", "realsociedad": "皇家社会",
  "gironafc": "赫罗纳", "赫罗纳": "赫罗纳", "吉罗纳": "赫罗纳", "girona": "赫罗纳",
  "realvalladolidcf": "巴利亚多利德", "巴利亚多利德": "巴利亚多利德", "realvalladolid": "巴利亚多利德",
  "deportivoalaves": "阿拉维斯", "阿拉维斯": "阿拉维斯", "alaves": "阿拉维斯",
  "udlaspalmas": "拉斯帕尔马斯", "拉斯帕尔马斯": "拉斯帕尔马斯", "laspalmas": "拉斯帕尔马斯",
  "cdleganes": "莱加内斯", "莱加内斯": "莱加内斯", "leganes": "莱加内斯",
  "cadizcf": "加的斯", "加的斯": "加的斯", "cadiz": "加的斯",
  "caosasuna": "奥萨苏纳", "奥萨苏纳": "奥萨苏纳", "osasuna": "奥萨苏纳",
  "granadacf": "格拉纳达", "格拉纳达": "格拉纳达", "granada": "格拉纳达",
  "rcdespanyoldebarcelona": "西班牙人", "西班牙人": "西班牙人", "espanyol": "西班牙人",
  "udalmeria": "阿尔梅里亚", "阿尔梅里亚": "阿尔梅里亚", "almeria": "阿尔梅里亚",
  // 意甲
  "acffiorentina": "佛罗伦萨", "佛罗伦萨": "佛罗伦萨", "fiorentina": "佛罗伦萨",
  "acmonza": "蒙扎", "蒙扎": "蒙扎", "monza": "蒙扎",
  "atalantabc": "亚特兰大", "亚特兰大": "亚特兰大", "atalanta": "亚特兰大",
  "bolognafc1909": "博洛尼亚", "博洛尼亚": "博洛尼亚", "bologna": "博洛尼亚",
  "cagliaricalcio": "卡利亚里", "卡利亚里": "卡利亚里", "cagliari": "卡利亚里",
  "como1907": "科莫", "科莫": "科莫", "como": "科莫",
  "empolifc": "恩波利", "恩波利": "恩波利", "empoli": "恩波利",
  "frosinonecalcio": "弗罗西诺内", "弗罗西诺内": "弗罗西诺内", "frosinone": "弗罗西诺内",
  "genoacfc": "热那亚", "热那亚": "热那亚", "genoa": "热那亚",
  "hellasveronafc": "维罗纳", "维罗纳": "维罗纳", "hellasverona": "维罗纳", "verona": "维罗纳",
  "parmacalcio1913": "帕尔马", "帕尔马": "帕尔马", "parma": "帕尔马",
  "sslazio": "拉齐奥",
  "torinofc": "都灵", "都灵": "都灵", "torino": "都灵",
  "udinesecalcio": "乌迪内斯", "乌迪内斯": "乌迪内斯", "udinese": "乌迪内斯",
  "uslecce": "莱切", "莱切": "莱切", "lecce": "莱切",
  "ussalernitana1919": "萨勒尼塔纳", "萨勒尼塔纳": "萨勒尼塔纳", "salernitana": "萨勒尼塔纳",
  "ussassuolocalcio": "萨索洛", "萨索洛": "萨索洛", "sassuolo": "萨索洛",
  "veneziafc": "威尼斯", "威尼斯": "威尼斯", "venezia": "威尼斯",
  // 德甲
  "1fcheidenheim1846": "海登海姆", "海登海姆": "海登海姆", "heidenheim": "海登海姆",
  "1fckoln": "科隆", "科隆": "科隆", "fckoln": "科隆", "koln": "科隆", "cologne": "科隆",
  "1fcunionberlin": "柏林联合", "柏林联合": "柏林联合", "unionberlin": "柏林联合",
  "1fsvmainz05": "美因茨", "美因茨": "美因茨", "mainz": "美因茨", "mainz05": "美因茨",
  "bayer04leverkusen": "勒沃库森", "勒沃库森": "勒沃库森", "leverkusen": "勒沃库森",
  "borussiamonchengladbach": "门兴", "门兴": "门兴", "门兴格拉德巴赫": "门兴", "gladbach": "门兴", "monchengladbach": "门兴",
  "fcaugsburg": "奥格斯堡", "奥格斯堡": "奥格斯堡", "augsburg": "奥格斯堡",
  "fcstpauli1910": "圣保利", "圣保利": "圣保利", "stpauli": "圣保利",
  "svdarmstadt98": "达姆施塔特", "达姆施塔特": "达姆施塔特", "darmstadt": "达姆施塔特",
  "svwerderbremen": "云达不莱梅", "云达不莱梅": "云达不莱梅", "不莱梅": "云达不莱梅", "werderbremen": "云达不莱梅", "bremen": "云达不莱梅",
  "tsg1899hoffenheim": "霍芬海姆", "霍芬海姆": "霍芬海姆", "hoffenheim": "霍芬海姆",
  "vflbochum1848": "波鸿", "波鸿": "波鸿", "bochum": "波鸿",
  "vflwolfsburg": "沃尔夫斯堡", "沃尔夫斯堡": "沃尔夫斯堡", "狼堡": "沃尔夫斯堡", "wolfsburg": "沃尔夫斯堡",
  // 法甲
  "ajauxerre": "欧塞尔", "欧塞尔": "欧塞尔", "auxerre": "欧塞尔",
  "angerssco": "昂热", "昂热": "昂热", "angers": "昂热",
  "asmonacofc": "摩纳哥", "摩纳哥": "摩纳哥", "monaco": "摩纳哥",
  "assaintetienne": "圣埃蒂安", "圣埃蒂安": "圣埃蒂安", "saintetienne": "圣埃蒂安",
  "clermontfoot63": "克莱蒙", "克莱蒙": "克莱蒙", "clermont": "克莱蒙",
  "fclorient": "洛里昂", "洛里昂": "洛里昂", "lorient": "洛里昂",
  "fcmetz": "梅斯", "梅斯": "梅斯", "metz": "梅斯",
  "fcnantes": "南特", "南特": "南特", "nantes": "南特",
  "lehavreac": "勒阿弗尔", "勒阿弗尔": "勒阿弗尔", "lehavre": "勒阿弗尔", "havre": "勒阿弗尔",
  "lilleosc": "里尔", "里尔": "里尔", "lille": "里尔",
  "montpellierhsc": "蒙彼利埃", "蒙彼利埃": "蒙彼利埃", "montpellier": "蒙彼利埃",
  "ogcnice": "尼斯", "尼斯": "尼斯", "nice": "尼斯",
  "racingclubdelens": "朗斯", "朗斯": "朗斯", "rclens": "朗斯", "lens": "朗斯",
  "rcstrasbourgalsace": "斯特拉斯堡", "斯特拉斯堡": "斯特拉斯堡", "strasbourg": "斯特拉斯堡",
  "stadedereims": "兰斯", "兰斯": "兰斯", "reims": "兰斯",
  "staderennaisfc1901": "雷恩", "雷恩": "雷恩", "rennes": "雷恩",
  "toulousefc": "图卢兹", "图卢兹": "图卢兹", "toulouse": "图卢兹",
  // 国家队(StatsBomb 世界杯)
  "argentina": "阿根廷", "阿根廷": "阿根廷",
  "australia": "澳大利亚", "澳大利亚": "澳大利亚",
  "belgium": "比利时", "比利时": "比利时",
  "brazil": "巴西", "巴西": "巴西",
  "cameroon": "喀麦隆", "喀麦隆": "喀麦隆",
  "canada": "加拿大", "加拿大": "加拿大",
  "colombia": "哥伦比亚", "哥伦比亚": "哥伦比亚",
  "costarica": "哥斯达黎加", "哥斯达黎加": "哥斯达黎加",
  "croatia": "克罗地亚", "克罗地亚": "克罗地亚",
  "denmark": "丹麦", "丹麦": "丹麦",
  "ecuador": "厄瓜多尔", "厄瓜多尔": "厄瓜多尔",
  "egypt": "埃及", "埃及": "埃及",
  "england": "英格兰", "英格兰": "英格兰",
  "france": "法国", "法国": "法国",
  "germany": "德国", "德国": "德国",
  "ghana": "加纳", "加纳": "加纳",
  "iceland": "冰岛", "冰岛": "冰岛",
  "iran": "伊朗", "伊朗": "伊朗",
  "japan": "日本", "日本": "日本",
  "mexico": "墨西哥", "墨西哥": "墨西哥",
  "morocco": "摩洛哥", "摩洛哥": "摩洛哥",
  "netherlands": "荷兰", "荷兰": "荷兰",
  "nigeria": "尼日利亚", "尼日利亚": "尼日利亚",
  "panama": "巴拿马", "巴拿马": "巴拿马",
  "peru": "秘鲁", "秘鲁": "秘鲁",
  "poland": "波兰", "波兰": "波兰",
  "portugal": "葡萄牙", "葡萄牙": "葡萄牙",
  "qatar": "卡塔尔", "卡塔尔": "卡塔尔",
  "russia": "俄罗斯", "俄罗斯": "俄罗斯",
  "saudiarabia": "沙特阿拉伯", "沙特阿拉伯": "沙特阿拉伯", "沙特": "沙特阿拉伯",
  "senegal": "塞内加尔", "塞内加尔": "塞内加尔",
  "serbia": "塞尔维亚", "塞尔维亚": "塞尔维亚",
  "southkorea": "韩国", "韩国": "韩国", "南韩": "韩国",
  "spain": "西班牙", "西班牙": "西班牙",
  "sweden": "瑞典", "瑞典": "瑞典",
  "switzerland": "瑞士", "瑞士": "瑞士",
  "tunisia": "突尼斯", "突尼斯": "突尼斯",
  "unitedstates": "美国", "美国": "美国", "usa": "美国",
  "uruguay": "乌拉圭", "乌拉圭": "乌拉圭",
  "wales": "威尔士", "威尔士": "威尔士",
};

const ALIAS_TABLE = Object.fromEntries(
  Object.entries(RAW_ALIASES).map(([raw, canonical]) => [normalizeRaw(raw), normalizeRaw(canonical)])
);

export function listKnownTeams() {
  return [...new Set(Object.values(ALIAS_TABLE))].sort();
}

export function aliasCoverage() {
  return {
    rawEntries: Object.keys(ALIAS_TABLE).length,
    canonicalTeams: listKnownTeams().length,
  };
}
